MODEL (
  name silverv1.fct_weekly_sales,
  kind FULL,
  cron '0 */3 * * *',
  owner 'shreyasikarwartmdcio',
  grains (week_start_date, region_id, category),
  description 'Weekly revenue and order aggregation by region and product category, with shipment and peak revenue flags.',
  tags ('silver', 'fact', 'weekly-sales', 'revenue', 'retail-intelligence'),
  terms ('sales.weekly_metrics', 'revenue.trends', 'retail.weekly_performance'),
  columns (
    week_start_date TIMESTAMP,
    year INTEGER,
    week_number INTEGER,
    region_id INTEGER,
    region_name VARCHAR(255),
    category VARCHAR(255),
    total_weekly_orders INTEGER,
    total_weekly_items INTEGER,
    total_weekly_revenue NUMERIC(15, 2),
    avg_daily_revenue NUMERIC(15, 2),
    max_daily_revenue NUMERIC(15, 2),
    min_daily_revenue NUMERIC(15, 2),
    active_customers INTEGER,
    shipment_days INTEGER,
    any_shipments_this_week BIT
  ),
  column_descriptions (
    week_start_date = 'Monday start of the ISO calendar week',
    year = 'Calendar year of the week',
    week_number = 'ISO week number within the year',
    region_id = 'Sales region identifier',
    region_name = 'Sales region name (North, South, East, West)',
    category = 'Product category label for the weekly aggregation row',
    total_weekly_orders = 'Total orders for the week-region-category grain',
    total_weekly_items = 'Total units sold in the week-region-category grain',
    total_weekly_revenue = 'Gross revenue for the week-region-category grain',
    avg_daily_revenue = 'Average daily revenue within the week',
    max_daily_revenue = 'Peak daily revenue in the week',
    min_daily_revenue = 'Lowest daily revenue in the week',
    active_customers = 'Distinct customers who ordered in the week grain',
    shipment_days = 'Number of daily rows in the week that had at least one shipment',
    any_shipments_this_week = 'True if any order in the week was shipped'
  ),
  column_tags (
    week_start_date = ('temporal', 'grain', 'time-series'),
    year = ('temporal', 'numeric'),
    week_number = ('temporal', 'numeric'),
    region_id = ('identifier', 'geography'),
    region_name = ('categorical', 'geography'),
    category = ('categorical', 'merchandising'),
    total_weekly_orders = ('numeric', 'volume'),
    total_weekly_items = ('numeric', 'volume'),
    total_weekly_revenue = ('numeric', 'revenue', 'financial'),
    avg_daily_revenue = ('numeric', 'revenue', 'average'),
    max_daily_revenue = ('numeric', 'revenue', 'peak'),
    min_daily_revenue = ('numeric', 'revenue', 'trough'),
    active_customers = ('numeric', 'engagement'),
    shipment_days = ('numeric', 'fulfillment'),
    any_shipments_this_week = ('boolean', 'fulfillment')
  ),
  column_terms (
    week_start_date = ('sales.week_start', 'retail.week_beginning'),
    year = ('calendar.year', 'time.year'),
    week_number = ('calendar.week_number', 'time.iso_week'),
    region_id = ('geography.region_id', 'sales.territory_id'),
    region_name = ('geography.region_name', 'sales.territory'),
    category = ('product.category', 'retail.merchandise_category'),
    total_weekly_orders = ('sales.weekly_orders', 'retail.weekly_order_count'),
    total_weekly_items = ('sales.weekly_units', 'retail.weekly_unit_volume'),
    total_weekly_revenue = ('sales.weekly_revenue', 'retail.gross_weekly_revenue'),
    avg_daily_revenue = ('sales.avg_daily_revenue', 'retail.average_daily_revenue'),
    max_daily_revenue = ('sales.peak_revenue', 'retail.max_daily_revenue'),
    min_daily_revenue = ('sales.trough_revenue', 'retail.min_daily_revenue'),
    active_customers = ('sales.weekly_active_customers', 'retail.active_buyers_per_week'),
    shipment_days = ('fulfillment.shipment_days', 'sales.days_with_shipments'),
    any_shipments_this_week = ('fulfillment.any_shipments', 'weekly_sales.shipped_flag')
  ),
  assertions (
    not_null(columns := (week_start_date, region_id, region_name, category)),
    forall(criteria := (total_weekly_orders >= 0, total_weekly_items >= 0, total_weekly_revenue >= 0))
  )
);

SELECT
  CAST(DATEADD(week, DATEDIFF(week, 0, order_date), 0) AS DATETIME2(6)) AS week_start_date,
  CAST(DATEPART(year, order_date) AS INTEGER) AS year,
  CAST(DATEPART(week, order_date) AS INTEGER) AS week_number,
  region_id,
  region_name,
  category,
  CAST(SUM(total_orders) AS INTEGER) AS total_weekly_orders,
  CAST(SUM(total_items_sold) AS INTEGER) AS total_weekly_items,
  ROUND(SUM(total_revenue), 2) AS total_weekly_revenue,
  ROUND(SUM(total_revenue) / NULLIF(COUNT(DISTINCT order_date), 0), 2) AS avg_daily_revenue,
  ROUND(MAX(total_revenue), 2) AS max_daily_revenue,
  ROUND(MIN(total_revenue), 2) AS min_daily_revenue,
  CAST(COUNT(DISTINCT customer_id) AS INTEGER) AS active_customers,
  CAST(COUNT(CASE WHEN has_shipment = 1 THEN 1 END) AS INTEGER) AS shipment_days,
  @boolean_flag(SUM(CASE WHEN has_shipment = 1 THEN 1 ELSE 0 END) > 0) AS any_shipments_this_week
FROM silverv1.fct_daily_sales
GROUP BY
  CAST(DATEADD(week, DATEDIFF(week, 0, order_date), 0) AS DATETIME2(6)),
  CAST(DATEPART(year, order_date) AS INTEGER),
  CAST(DATEPART(week, order_date) AS INTEGER),
  region_id,
  region_name,
  category;
